runtime: python
threadsafe: yes
env: flex
entrypoint: gunicorn -b :$PORT app:app

runtime_config:
  python_version: 3

env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    SQLALCHEMY_DATABASE_URI: >-
      postgresql+psycopg2://postgres:password@/postgres?host=/cloudsql/cs329e-187400:us-central1:cs329e-db
beta_settings:
  cloud_sql_instances: 'cs329e-187400:us-central1:cs329e-db'

handlers:
- url: /.*
  script: app.app
